### ISSUE TITLE
Permission issues with UIDs different from 1000

### ISSUE THREAD

**Issue by domire8** [aica-technology/docker-images#78]
It is possible that some linux users have UID/GID different from 1000, e.g. when they are not the first user created on the system. This leads to permission issues with the filesystem because the `ros2` user of the aica-docker images has UID/GID 1000.

It would be nice to be able to set the UID and GID according to the local user that is creating the interactive session. The 'server' case is not affected by this, because we launch it with user `root`

**Comment by domire8** [comment]
@LouisBrunner i'd like to make you aware of this issue here. Our current backend and application images work a lot with the filesystem of the host through volume sharing and if the UID/GID of the host and the docker user are not the same, things just get messed up. One way to solve this would be to not interact with the filesystem anymore but that seems like a long term goal. In the short term, we should somehow try to account for this.

**Comment by LouisBrunner** [comment]
@domire8 Is it just the case to get users to set `--uid` and `--gid` when they start the image?

Otherwise, I imagine you can probably get away with forwarding logs through docker and maybe users don't need to have access to your DB/internal files anyway. I guess you could also get all configuration/file exports done in the Front-End and avoid this issue...

**Comment by domire8** [comment]
> Is it just the case to get users to set `--uid` and `--gid` when they start the image?

No, because the docker images on docker-images are built with a user that has uid and gid 1000. There are also some files (example applications) that are copied into the backend image just at the end. If you then start the backend from a host user with 1001, all the files will have wrong ownership and editing/creating files on shared volumes will be problematic.

For now, what I do is the following ([at the very top of the backend image](https://github.com/aica-technology/backend/blob/1d3cfc3b57e7d7006fb88d4e8f0da8aca8d21819/Dockerfile#L6))
```
USER root
RUN usermod -u 1001 ${USER} && groupmod -g 1001 ${USER} && chown -R ${USER}:${USER} ${HOME}
```

**Comment by LouisBrunner** [comment]
Good point, however this is usually only an issue when writing files. Do you need to write in a lot of different places when using ROS? Otherwise, you could standardize a single folder with all your data, e.g. `/data` and make sure that that one is always writable.

**Comment by domire8** [comment]
Hm yeah that would be one possible solution but especially in development/testing we sometimes share volumes to specific packages in the ROS workspace such that we can change the source code on the host and directly rebuild inside the container. But maybe this issue is also more about improving our workflows for that particular situation than anything else..Because apart from that it would be easy to just say all the shared data is in one place

**Comment by domire8** [comment]
@LouisBrunner @eeberhard We need to talk about this again now that we are going towards a proper packaging script. It's still a real problem IMO. Either we can guarantee that there are no filesystem interactions (unlikely, especially for developers), or we need something like
```
RUN usermod -u 1001 ${USER} && groupmod -g 1001 ${USER} && chown -R ${USER}:${USER} ${HOME}
```
in the backend build script and/or in the api packaging script.

I would probably propose to make the UID a build arg and then make an `if` logical block in the dockerfile that changes permissions if the (automatically) passed uid is different from 1000 (and this in both backend build and api package). It will take a few secs (I'm doing that reguraly on our NUCs), but it's way faster than before because we have less files under home

**Comment by LouisBrunner** [comment]
I don't really have a problem with that approach, but I just want to clear up a few things.

> unlikely, especially for developers

Is that AICA developers?

> there are no filesystem interactions

What files do you usually write to?

**Comment by domire8** [comment]
Tough questions, for now there are only AICA developers and we still don't really know how others would develop. But if you record some topics for example, that's a case where we write to files, or if we create new apps inside the container or so.

**Comment by LouisBrunner** [comment]
Is there any way for us to standardize these paths so we can have a clear place where things are written in/out of the image?

**Comment by domire8** [comment]
So I have to bring this up again. Here's the situation:
I'm on a NUC on a user account with UID/GID 1001, and I build a backend with a bunch of components and collections with an aica-package.toml. Now I want to run this and mount a `data` directory that I created since this is required. However, this now doesn't work since the local directory has UID/GID 1001 whereas the `/data` directory in the container has UID/GID 1000. It's a pain but we need to tackle this somehow with an extra step. Is there a way that at the end of `docker build -f aica-package.toml` we could check for non-matching UID/GID?

**Comment by domire8** [comment]
@bpapaspyros FYI

**Comment by LouisBrunner** [comment]
> Is there a way that at the end of `docker build -f aica-package.toml` we could check for non-matching UID/GID?

`/data` is not available during `docker build` so I am not sure how that would be possible?

**Comment by domire8** [comment]
> `/data` is not available during `docker build` so I am not sure how that would be possible?

`/data` is created [here](https://github.com/aica-technology/backend/blob/b7abdd43062e6644153d3ab4163247e70e221b6d/Dockerfile#L49) so it is available, its even created on build.

I don't know in detail how the app-builder works but couldn't we add a stage after it copies all required dependencies that checks if the UID of the user is different from 1000 and then change that, just like we do in the base Dockerfile of the backend?

```
RUN <<EOF
set -e

if [ "${UID}" = 1000 ] && [ "${GID}" = 1000 ]; then
  set +e
  exit 0
fi

usermod -u ${UID} ${USER} && groupmod -g ${GID} ${USER} && chown -R ${USER}:${USER} ${HOME}
EOF
```

**Comment by LouisBrunner** [comment]
> `/data` is created [here](https://github.com/aica-technology/backend/blob/b7abdd43062e6644153d3ab4163247e70e221b6d/Dockerfile#L49) so it is available, its even created on build.

Sorry for going backward again but I think this is a losing battle. Trying to match our internal UID to whatever the user's is hasn't worked so far and I can't see us finding a foolproof way to avoid the issue.

Maybe we should consider setting up something like rootless containers use, e.g. `subuid` https://rootlesscontaine.rs/getting-started/common/subuid/

> I don't know in detail how the app-builder works but couldn't we add a stage after it copies all required dependencies that checks if the UID of the user is different from 1000 and then change that, just like we do in the base Dockerfile of the backend?

`app-builder` itself runs within Docker so we don't have access to the UID/GID of the user running the command.

**Comment by domire8** [comment]
I don't want to accept defeat haha...

> app-builder itself runs within Docker so we don't have access to the UID/GID of the user running the command.

Fair enough, what if the user could at least provide build args if there is a mismatch?

`docker build -f aica-package.toml --build-arg config.uid=$(id -u)`

**Comment by LouisBrunner** [comment]
> I don't want to accept defeat haha...

It's not giving up, it's another approach. I went through some of the most popular Docker images (e.g. MySQL, Postgres, Wordpress) and the way they do that is by handling it at run-time (because that's when you know the actual UID).

Take a look at this https://github.com/docker-library/postgres/pull/253 or this https://github.com/docker-library/docs/blob/master/postgres/README.md#arbitrary---user-notes.

The idea is to let `root` be the default user. If the user doesn't set `-u` when doing `docker run`, then we can chown `/data` with `ros2` and run the daemons. If the user uses `-u` then we can create our folders like expected.

Is there anywhere we need to write apart from `/data`? `$HOME` should be readable in all cases (and if it isn't we can change that).

I think there is value in aligning with what the rest of the industry does, as it will match closer to what a typical user will expect and it will be easier for them to find help instead of a very non-standard approach.

> Fair enough, what if the user could at least provide build args if there is a mismatch?
> 
> `docker build -f aica-package.toml --build-arg config.uid=$(id -u)`
> 
> It would be a start for the NUCs downstairs at least

We could do that.

**Comment by domire8** [comment]
Sooo while our standard user would only mount `/data`, I still mount some stuff into the home folder when I work with the backend. That's why I would like to change not just `/data` but the whole home folder. It's already readable yes, but having the option to write would be cool too. Okay, while writing this sentence I realize that I don't need two different mounts, I can also mount the examples directory to `/data`. So okay let's say its just `/data` that we need to focus on for now.

Hm I'm  not sure what undesired side effects it would have if we run ROS as root, I don't think that works well (ROS as root in general).

**Comment by LouisBrunner** [comment]
> Sooo while our standard user would only mount `/data`, I still mount some stuff into the home folder when I work with the backend. That's why I would like to change not just `/data` but the whole home folder. It's already readable yes, but having the option to write would be cool too. Okay, while writing this sentence I realize that I don't need two different mounts, I can also mount the examples directory to `/data`. So okay let's say its just `/data` that we need to focus on for now.

In any case, the only issue is really if _both_ you and the app need to write the same folder. If we ensure `/data` is always writable to the app, it doesn't really matter too much if it's writable to you? Vice versa for $HOME.

> Hm I'm not sure what undesired side effects it would have if we run ROS as root, I don't think that works well (ROS as root in general).

ROS (or any of our applications) would never run as root, only the entrypoint.

**Comment by domire8** [comment]
> In any case, the only issue is really if _both_ you and the app need to write the same folder. If we ensure `/data` is always writable to the app, it doesn't really matter too much if it's writable to you? Vice versa for $HOME.

Sure I guess that makes sense.

> ROS (or any of our applications) would never run as root, only the entrypoint.

I see :+1:

**Comment by LouisBrunner** [comment]
Summary of our offline chat:

* We will stop trying to match the uid/gid of the `ros2` user inside the container with the one running `docker run`
* This means we are currently happy with the `/data` being owned by the wrong user on the host computer
* The backend will be responsible for ensuring the `/data` has correct ownership at startup, for now `docker run --user` will not be supported and will be introduced if/when required
* CL and NI will be updated to avoid clobbering the rights of `~ros2`, this is more of a best practice than a requirement however

Thus:

* `/data` will always be writable by `ros2` inside the container but not necessarily outside it
* `~ros2` should be writable most of the time but it isn't required for it to be, thus other root-owned folders can be mounted there (e.g. `~ros2/examples`)

FYI @bpapaspyros @eeberhard

**Comment by eeberhard** [comment]
Thanks for the discussion and summary. I agree with the direction of the outcome.
