### ISSUE TITLE
Add version to docker-images

### ISSUE THREAD

**Issue by domire8** [aica-technology/docker-images#82]
As title suggests. Best option would be a workflow that updates the version on push to main.

**Comment by domire8** [comment]
comment from @eeberhard 
> As a side note, how do you feel about tagging the ros2-control image with the version (for example, as :iron and :iron-3.18)? That way if we keep iron but upgrade ros2_control to some other version later, we can distinguish them. Not in scope for this PR but goes in a similar direction and I think would be useful to do.

comment from @LouisBrunner 
> I think we should just make our own version for this. e.g. v2.3.0+iron

comment from me:
> Fair suggestion, do we take the version from a VERSION file?

**Comment by LouisBrunner** [comment]
I don't mind where we get the version at the moment, as long as we produce 2 tags (`v2.3.0+iron` and `v2.3.0`, as it makes package management easier later). I don't mind which of these tags is the ones that makes it into git either.

**Comment by LouisBrunner** [comment]
Iron and humble would be different versions, e.g. `v1.4.5+humble` and `v2.3.1+iron`. There is no reason for them to be linked (after all they aren't necessarily compatible).

**Comment by domire8** [comment]
A couple of weeks ago, we decided that in the near future, we'll drop the `ros2-control` image and only ship one `ros2-ws` image that contains all dependencies we need for ROS2 and ROS2 Control. @LouisBrunner What would be your suggestion for the tags of the image? `vX.Y.Z+ROS_DISTRO`? I think we could already start to set that up.

**Comment by LouisBrunner** [comment]
So the new `ros2-ws` will be equivalent to the old `ros2-control`?

Yeah I think a version like that makes sense.

**Comment by domire8** [comment]
Name is not 100% sure but yeah essentially that's it.

**Comment by domire8** [comment]
The `+` is not allowed in docker images tags though it seems

**Comment by LouisBrunner** [comment]
Ah, that's a shame. I guess we can do multi-tags and include `vX.Y.Z`, `vX.Y.Z-ROS_DISTRO` and `ROS_DISTRO` and that should be both standard Docker and mostly semver-compliant.
