### ISSUE TITLE
Try Docker setup with VS Code

### ISSUE THREAD

**Issue by domire8** [aica-technology/docker-images#91]
It would be great to "replicate" the SSH setup we have for CLion in VS code with the Docker toolchain.

**Comment by domire8** [comment]
@eeberhard could you give me a few hints which environment variables I have to play around with?

**Comment by domire8** [comment]
I think I'm on track to find a good setup with VS code dev containers that everyone can use. What will be required is a `.devcontainer` and `.vscode` directory that contain the required configuration files for the devcontainer.

A small drawback of VS code is that clang formatting only works with a `.clang-format` that is in the workspace of the projects. So there are two options:
1. put the .clang-format file into the `.vscode` directory
2. make the .clang-format file available in our base docker image
Option 1 comes with the main drawback that the file will potentially be copied to many different places, which is why option 2 would be quite neat IMO. 

I could imagine that the `ros2_ws` downloads the clang-format file from our .github repo and puts it into the home folder

**Comment by eeberhard** [comment]
Yes, if it reads the format file from the container filesystem, then it should be pulled into the base image from the repo automatically. That would make things very portable. Nice progress!

**Comment by domire8** [comment]
I think we handled this quite well :+1: It's not done for every repo but we know that it works
