### ISSUE TITLE
Consolidate images into one base image

### ISSUE THREAD

**Issue by domire8** [aica-technology/docker-images#98]
As discussed as part of a different initiative (public base class for modulo controllers), it was agreed that there should only be one `ROS2` base image that contains all the sources for ROS2 and ROS2 Control. This has several advantages, mainly that we don't need to keep track of an additional intermediate image and that then all our repositories using ROS can use a tagged version of that one single image (see also #82).

I don't think this needs to be an epic, but the steps would be:
1. Tag the current state of the repo as v1.0.0 (done)
2. Remove Dockerfiles of deprecated images (not the images on GHCR itself!)
3. Merge Dockerfiles of `ros2-ws` and `ros2-control`
4. Update README
5. Release the new base image with the current tags of ros2-control as `v1.0.0+iron`

@eeberhard @bpapaspyros @LouisBrunner

**Comment by LouisBrunner** [comment]
Just a reminder: as discussed in #82 we should have multiple tags for each release for maximum discoverability.
